### ISSUE TITLE
fluffy machines outdates

### ISSUE THREAD

**Issue by vRAPTORv** [NCBPFluffyBear/FluffyMachines#148]
## Description (Required)
when we updates the server to 1.20.4 fluffy machines vDEV - 132 wont work

#141

**Comment by NCBPFluffyBear** [comment]
Your linked issue should be unrelated, 1.20.4 caused some issues and were fixed recently. New builds are now located on https://blob.build/project/FluffyMachines, and will require a manual update. Please let me know if you still can not load the plugin after updating!

**Comment by DreadfulValerian** [comment]
+1, unfortunately it's not loading after updating to the new build- we're on Paper, if it helps!

**Comment by NCBPFluffyBear** [comment]
What version are you on? Please send `/sf versions` output

**Comment by DreadfulValerian** [comment]
Fluffy Machines vDev - 4

**Comment by NCBPFluffyBear** [comment]
Please also share console errors

**Comment by DreadfulValerian** [comment]
![image](https://github.com/NCBPFluffyBear/FluffyMachines/assets/134436513/6c936676-64e7-4092-9629-6eef635027fa)
[07.02 15:12:15] [Server] [ERROR] Error occurred while enabling FluffyMachines vDEV - 132 (git ccf029ba) (Is it up to date?)
[07.02 15:12:15] [Server] java.lang.NoSuchMethodError'boolean org.bukkit.enchantments.Enchantment.isAcceptingRegistrations()'
[07.02 15:12:15] [Server] 	at io.ncbpfluffybear.fluffymachines.FluffyMachines.onEnable(FluffyMachines.java:61) ~[FluffyMachines - DEV (git ccf02).jar:?]
[07.02 15:12:15] [Server] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[07.02 15:12:15] [Server] 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[07.02 15:12:15] [Server] 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-409]
[07.02 15:12:15] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07.02 15:12:15] [Server] [INFO] [FluffyMachines] Disabling FluffyMachines vDEV - 132 (git ccf029ba)

**Comment by NCBPFluffyBear** [comment]
Those errors clearly say "FluffyMachines vDEV - 132". Update your plugin.

**Comment by DreadfulValerian** [comment]
That's the latest version from blob.build. There may have been a mixup with file uploads on your end, but I've tried four times the latest file from it now.

**Comment by NCBPFluffyBear** [comment]
You might have a duplicate FluffyMachines file. The latest build has been released for more than a month now with no issues from other people. If you were really running the latest version, your error would show the correct version, like this:

![image](https://github.com/NCBPFluffyBear/FluffyMachines/assets/31554056/b7c3bf60-5514-49b9-ab89-d4e887e59151)

The error message is different, but the point is that the tag shows the build. The build you are running is from Sep 2, 2022.
I just downloaded the latest paper version, Slimefun build, and FluffyMachines build and it worked. The line of code that your error shows does not even exist.

**Comment by DreadfulValerian** [comment]
I tried getting another person to download it, culled anything with Fluffy in the name, and it still won't load, though it appears to now be the version from blob.build
![image](https://github.com/NCBPFluffyBear/FluffyMachines/assets/134436513/bd8dd834-d5ce-4c72-86d5-69e1c005386d)

**Comment by NCBPFluffyBear** [comment]
Looks the it's the right version now. Does your server have custom vanilla crafting recipes?

**Comment by DreadfulValerian** [comment]
Yes, it does. Are there specific ones/types I'll have to terminate or fix?

**Comment by DreadfulValerian** [comment]
Figured out how to fix the problem, but disabled a swath of datapacks to do so- is there a specific thing I can remove from a handful of datapacks to get it to work? No worries if you don't know, and sorry for all the trouble ^^'

**Comment by DreadfulValerian** [comment]
Okay, found it- the Forgiveness datapack appears to be incompatible with FluffyMachines, posting so this is Googlable :P

**Comment by NCBPFluffyBear** [comment]
I'll look into this
